# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# find_suitable_land_parameters.py
# Created on: 2018-04-19 12:19:35.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: find_suitable_land_parameters <Cities> <Roads> <Boundaries> <Suitable_land> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Cities = arcpy.GetParameterAsText(0)

Roads = arcpy.GetParameterAsText(1)

Boundaries = arcpy.GetParameterAsText(2)

Suitable_land = arcpy.GetParameterAsText(3)
if Suitable_land == '#' or not Suitable_land:
    Suitable_land = "E:\\Python\\arcpy_folder1\\p_5\\PythEveryone10_11\\Lesson1\\Lesson1\\USA.gdb\\suitable_land_1" # provide a default value if unspecified

# Local variables:
Cities_buffer_distance = "10 Miles"
Buffered_cities = "E:\\Python\\arcpy_folder1\\p_5\\PythEveryone10_11\\Lesson1\\Lesson1\\USA.gdb\\us_cities_Buffer"
Roads_buffer_distance = "10 Miles"
Buffered_roads = "E:\\Python\\arcpy_folder1\\p_5\\PythEveryone10_11\\Lesson1\\Lesson1\\USA.gdb\\us_roads_Buffer"
Intersected_buffers = "E:\\Python\\arcpy_folder1\\p_5\\PythEveryone10_11\\Lesson1\\Lesson1\\USA.gdb\\us_buffer_interset"

# Process: Buffer the cities
arcpy.Buffer_analysis(Cities, Buffered_cities, Cities_buffer_distance, "FULL", "ROUND", "ALL", "", "GEODESIC")

# Process: Buffer the roads
arcpy.Buffer_analysis(Roads, Buffered_roads, Roads_buffer_distance, "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Intersect
arcpy.Intersect_analysis("E:\\Python\\arcpy_folder1\\p_5\\PythEveryone10_11\\Lesson1\\Lesson1\\USA.gdb\\us_cities_Buffer #;E:\\Python\\arcpy_folder1\\p_5\\PythEveryone10_11\\Lesson1\\Lesson1\\USA.gdb\\us_roads_Buffer #", Intersected_buffers, "ALL", "", "INPUT")

# Process: Clip
arcpy.Clip_analysis(Intersected_buffers, Boundaries, Suitable_land, "")

