# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Nebrasca.py
# Created on: 2018-04-26 09:37:27.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.env.overwriteOutput = True
Precipitation = arcpy.GetParameterAsText(0)
Nebraska__2_= arcpy.GetParameterAsText(1)
Nebrasca_precip_shp = arcpy.GetParameterAsText(2)

# Local variables:
#Precipitation = r"E:\Python\arcpy_folder1\p_5\PythEveryone10_11\Lesson1\Lesson1\USA.mdb\Precip2008Readings"
idw_precipitation = "E:\\Python\\arcpy_folder1\\p_5\\PythEveryone10_11\\Lesson1\\Lesson1\\USA.mdb\\idw_precipitation"
reclass = "E:\\Python\\arcpy_folder1\\p_5\\PythEveryone10_11\\Lesson1\\Lesson1\\USA.mdb\\reclass"
RasterT_Reclass1 = r"E:\Python\arcpy_folder1\p_5\PythEveryone10_11\Lesson1\Lesson1\RasterT_Reclass1.shp"
#Nebraska__2_ = "E:\\Python\\arcpy_folder1\\p_5\\PythEveryone10_11\\Lesson1\\Lesson1\\USA.mdb\\Nebraska"
#Nebrasca_precip_shp = "E:\\Python\\arcpy_folder1\\p_5\\PythEveryone10_11\\Lesson1\\Lesson1\\code\\Nebrasca_precip.shp"

# Process: IDW
arcpy.gp.Idw_sa(Precipitation, "RASTERVALU", idw_precipitation, "1850,46466995651", "2", "VARIABLE 12", "")

# Process: Reclassify
arcpy.gp.Reclassify_sa(idw_precipitation, "VALUE", "27715,960938 46615,086060 1;46615,086060 64536,670227 2;64536,670227 82132,407410 3;82132,407410 111132,789063 4", reclass, "DATA")

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(reclass, RasterT_Reclass1, "SIMPLIFY", "VALUE")

# Process: Clip
arcpy.Clip_analysis(RasterT_Reclass1, Nebraska__2_, Nebrasca_precip_shp, "")
